### ISSUE TITLE
GPG Support

### ISSUE THREAD

**Issue by BrendanThompson** [elasticdog/transcrypt#10]
It would be good to have GPG support that is one of the main benefits of git-crypt. Is there any chance of that?

**Comment by adrianduke** [comment]
I've created a PR with basic GPG import/export features:

https://github.com/elasticdog/transcrypt/pull/20

(yeah, forgot to reference this issue in any of the commits)

**Comment by elasticdog** [comment]
@BrendanThompson I've recently merged in the `--export-gpg` and `--import-gpg` command line flags to dump the transcrypt configuration to a GPG-encrypted file, and to conversely read a GPG-encrypted file to get the configuration details when setting things up. The feature is in the master branch for now, and will be included in the upcoming 0.9.8 release.

I believe this is similar to what git-crypt does and should resolve this issue.
