### ISSUE TITLE
Broken macOS tests: latest macOS release 11.2.2 Big Sur has newer OpenSSL and Git versions?

### ISSUE THREAD

**Issue by jmurty** [elasticdog/transcrypt#115]
This is most likely a problem in GitHub's `macos-latest` test OS feature, but there is also a chance that the latest macOS release 11.2.2 upgrades OpenSSL and Git in significant ways.

I have been pushing changes and triggering tests tonight, then all of a sudden I started getting strange failures for just the macOS test runs and the following outputs:

- OpenSSL version `1.1.1j` (my version is `LibreSSL 2.8.3` on macOS 11.2.1)
- A new `hint` warning from Git about the default branch name

<img width="1137" alt="Screen Shot 2021-02-27 at 11 51 00 pm" src="https://user-images.githubusercontent.com/65604/109387782-719a8600-7957-11eb-8032-bb93c34f0cb5.png">

**Comment by jmurty** [comment]
The macOS release notes for 11.2.2 are too vague to give any useful details, and the linked web site doesn't (yet) even show 11.2.2 notes for me:

> macOS Big Sur 11.2.2 11.2.2 — **Restart Required**
>
> macOS Big Sur 11.2.2 prevents MacBook Pro (2019 or later) and MacBook Air (2020 or later) models from incurring damage when they are connected to certain third-party, non-compliant powered USB-C hubs and docks.
>
> For more detailed information about this update, please visit: https://support.apple.com/HT211896

**Comment by jmurty** [comment]
Closing this, the test failures were my user error.

GitHub does use a newer OpenSSL version that is actually provided by default with macOS, so that's something to be wary of in a testing context, but now that I have upgraded to 11.2.2 myself I can confirm that the OpenSSL version provided by Apple by default remains old :( 
```bash
$ openssl version
LibreSSL 2.8.3
```

**Comment by elasticdog** [comment]
Very interesting that GitHub chooses to update the version of OpenSSL on the Mac runners...definitely good to know for future reference.

Related to the hint output, I'd certainly be on board for updating the default branch from `master` to `main`. GitHub did recently release their [tooling to seamlessly rename branches](https://github.blog/changelog/2021-01-19-support-for-renaming-an-existing-branch/), so we could do it and not cause too much disruption.
