### ISSUE TITLE
How to handle hidden file in crypt ?

### ISSUE THREAD

**Issue by rioukkevin** [elasticdog/transcrypt#124]
Hi, 
I don't find information on how to handle file like .npmrc at project root in transcrypt, does anyone know how ? 
Thanks for your help
Have a nice day and be happy :wink:

**Comment by jmurty** [comment]
Hi @rioukkevin if you want to encrypt files like `.npmrc` with transcrypt you [add a matching "crypt" pattern to the `.gitattributes` file](https://github.com/elasticdog/transcrypt#designate-a-file-to-be-encrypted).

Add a line like the following to `.gitattributes`, then `git add .gitattributes .npmrc` and commit to (re-)add these files to Git:

```
# In .gitattributes file
.npmrc filter=crypt diff=crypt merge=crypt
```

Run `git ls-crypt` to make sure the files you want to encrypt are actually being handled by transcrypt.

Be careful when adding patterns for dot-files not to add accidentally encrypt file paths that are important to Git or transcrypt. Do **not** add a pattern like `.*` to `.gitattributes`. Adding hidden file patterns one-by-one is probably safest.

**Comment by rioukkevin** [comment]
Thank you, I'll try it
