### ISSUE TITLE
smudge issue

### ISSUE THREAD

**Issue by narkisr** [elasticdog/transcrypt#14]
I keep getting:

```bash
error: external filter "$(git rev-parse --show-toplevel)"/.git/crypt/smudge failed 1
error: external filter "$(git rev-parse --show-toplevel)"/.git/crypt/smudge faile
```

While running git diff

My attributes file includes:

```bash
#pattern  filter=crypt diff=crypt
manifests/hosts/*.pp filter=crypt diff=crypt
data/*.yaml filter=crypt diff=crypt
```

**Comment by elasticdog** [comment]
Do any of your encrypted files happen to be empty? I believe that will trigger the above error (see #27 for some details). I'll close this out as I've not heard back with reproducible steps, but please do post if you've got more information.
