### ISSUE TITLE
 is it possible to use a password to allow only committer who known it to decipher files

### ISSUE THREAD

**Issue by LuisBL** [elasticdog/transcrypt#151]
question: is it possible to use a password to allow only committer who known it to decipher files ?

I understand that by default the password is "automatic" so all user with access to the repo will be able to see the ciphered files (un-ciphered)

**Comment by jmurty** [comment]
Hi,

Only people with the password can decipher secret files. So in your case, you can keep the password to yourself and no-one else will be able to read the file contents unless they are using the same computer and directory. 

The automatic decrypt feature only works once transcrypt is initialised – and the password entered – for each cloned repository.

**Comment by LuisBL** [comment]
My bad I didn't understood this at first, Thank you I close this issue
