### ISSUE TITLE
encryption changed, but no change!

### ISSUE THREAD

**Issue by njfamirm** [elasticdog/transcrypt#164]
hi

Sometimes it shows the files with changes while there are no changes!
and `git diff` does not show anything.

why happen?
I clone repo.

**Comment by jmurty** [comment]
Hi, which version of transcrypt are you using? And are you sure you're using the latest version in all your repositories?

The latest 2.2.3 release has some fixes for incompatibilities with newer versions of OpenSSL (3+)

**Comment by AliMD** [comment]
@elasticdog could you please check this issue. thank you.

**Comment by jmurty** [comment]
Try the latest version which is 2.2.3

**Comment by njfamirm** [comment]
thnaks, fixed
