### ISSUE TITLE
Support for git archives

### ISSUE THREAD

**Issue by KenRud** [elasticdog/transcrypt#18]
I just started using transcrypt recently and really like what it has to offer. One feature that I would really like to see is support for git archives. My particular use case is for [Capistrano](https://github.com/capistrano/capistrano) deployment to a remote server. Capistrano clones the git repository with the --mirror option to a local repo folder. It then calls "git update" to update the repo when needed. For deploying new releases it will use "git archive" on its local repo mirror and extract the output to a release directory. I would try to implement support for this myself but I am rather unfamiliar with the SSL encryption libraries and how Git filtering works.

**Comment by elasticdog** [comment]
I'm definitely not familiar with using `git archive` or Capistrano, but from my experiments locally using Git v2.3.5, it looks like if the repo is configured with transcrypt and things are decrypted, the archive it produces will also keep the file decrypted (which is your desired outcome). Are you able to inject a step in the process to have Capistrano clone with `--mirror` and then configure transcrypt before the actual archive creation/deployment?

**Comment by KenRud** [comment]
Yes I have tried that approach. The issue is that when I try to run the transcrypt command on the mirrored repo it tells me that I am not in a git working directory. The `--mirror` option is very similar to the `--bare` option and it seems like transcrypt does not recognize these types of clones.

I will try to run transcrypt locally on my machine against a mirrored repo and let you know exactly what happens.

**Comment by elasticdog** [comment]
> The --mirror option is very similar to the --bare option and it seems like transcrypt does not recognize these types of clones.

Ahhh, gotcha. That is something I can look into.

**Comment by elasticdog** [comment]
I'm afraid I haven't come up with a good solution to this issue. I've done some reworking to try and get a bare repository configured with transcrypt, but even with that, the git-archive command doesn't pay attention to the attributes when generating an archive. There are some attributes that git-archive pays attention to [1], but I haven't been able to get that working with a bare repo (even when setting things in the `info/attributes` file). I'll keep messing around with it, but there might not be a clean way to utilize Capistrano's default deployment method and have things decrypted in the final directory without some real shenanigans.

[1] https://git-scm.herokuapp.com/docs/git-archive#ATTRIBUTES

**Comment by KenRud** [comment]
Ok, thank you for looking into the issue. I have found a temporary work-around that is specific to Capistrano, but it is not ideal. I am basically uploading my local unencrpyted copy of a secure file rather than using the file that Capistrano pulls from the repo.

**Comment by elasticdog** [comment]
I poked at this a bit more without any luck. I'm going to close this for now, but will think about the archive use case moving forward if new options come about.

**Comment by elasticdog** [comment]
Per

**Comment by elasticdog** [comment]
I spoke a bit too soon, and I think that if I make some tweaks to allow transcrypt to configure bare repositories, then git archive actually will honor the attributes settings and I was able to export a tarfile that had the decrypted files in it. I have some more testing to do but will post back once I push the branch so you can try it out (if you're still interested in a solution).
