### ISSUE TITLE
error when running transcrypt on a fresh clone

### ISSUE THREAD

**Issue by oz123** [elasticdog/transcrypt#19]
```
(frank)[280] oti@core-dev:~/Software/tesf  [master]  $   transcrypt -c aes-256-cbc -p 'foo bar secret'

The following configuration will be saved:

  REPO:     /home/oti/Software/tesf
  CIPHER:   aes-256-cbc
  PASSWORD: foo bar secret

Does this look correct? [Y/n] 


error: external filter "$(git rev-parse --show-toplevel)"/.git/crypt/smudge failed 1
error: external filter "$(git rev-parse --show-toplevel)"/.git/crypt/smudge failed
The repository has been successfully configured by transcrypt.
```

This also happens when trying git diff:
```
(frank)[284] oti@core-dev:~/Software/tesf  [master]  $ git diff
error: external filter "$(git rev-parse --show-toplevel)"/.git/crypt/smudge failed 1
error: external filter "$(git rev-parse --show-toplevel)"/.git/crypt/smudge failed
```

**Comment by elasticdog** [comment]
I've normally seen this happen if somebody staged a file in the repository before adding the crypt filter in the `.gitattributes` file. If you pull the latest version of transcrypt from this repo (I haven't tagged a new release yet), I've [added a feature](https://github.com/elasticdog/transcrypt/commit/a0b7d4ec0296e83974cb02be640747149b23ef54) to help debug this, it dumps the raw commit objects for all of the files that should be encrypted. Essentially you can run:

```
$ transcrypt --show-raw '*'
```
...and then look for the file that's still in plain text, and that's you're culprit.

**Comment by oz123** [comment]
This seems to solve the problem, but I am not sure about it. Anyway, I got transcrypt too work after a bumpy ride.
