### ISSUE TITLE
support add patches to commit with git add -i

### ISSUE THREAD

**Issue by oz123** [elasticdog/transcrypt#21]
Currently this is not working, and will display the patches in the pager as encrypted text.

**Comment by elasticdog** [comment]
Unfortunately, there's not a way to just edit a patch of an encrypted file as the encryption happens at the file-level, so any changed content within the file will change the entire resulting output. The individual sections of the file cannot be isolated.

To make that limitation more clear, in #29, I'm properly marking the files as binary so Git will at least tell you that it won't work:

    $ git add -p
    Only binary files changed.
