### ISSUE TITLE
Problems with `git worktree`.

### ISSUE THREAD

**Issue by tvaughan** [elasticdog/transcrypt#22]
transcrypt's use of `git rev-parse --show-toplevel` in `.git/config` doesn't work with `git worktree`[1]. It appears, from my very limited testing, that `git rev-parse --git-common-dir` should be used instead. This works in both the linked and master worktree (in the top-level directories as well as subdirectories within each worktree).

[1] https://github.com/blog/2042-git-2-5-including-multiple-worktrees-and-triangular-workflows

**Comment by elasticdog** [comment]
Hey @tvaughan, thanks for the heads up! Sorry it has taken forever to respond to this, I was offline taking time off in between jobs, then traveling for two of the past four weeks and just now catching up on personal projects. The new experimental *worktree* feature sounds a lot like what you were doing with the `contrib/workdir/git-new-workdir` before...super handy.

A couple of concerns with using `--git-common-dir` is that (as far as I can tell), it was only introduced in November of last year (in version 2.2.0), so on common platforms like Ubuntu 14.04 LTS, users won't have that option available to them without explicitly installing a newer version of Git. Also briefly scanning through transcypt's use of the `$REPO` variable, there might be some cases where it makes sense to point to the common directory, and others when it does not...so I'd have to go through each one and ensure that's what we want or if two variables would be needed.

Either way, give me some more time to play around with the worktree stuff myself and kick the tires to see how transcrypt is behaving. If worse comes to worse, and we need to add a conditional to test versions and set things up slightly differently, then I'll try and think of a clean way to do that. I appreciate the feedback.
