### ISSUE TITLE
Multiple keys, same repo

### ISSUE THREAD

**Issue by charliewolf** [elasticdog/transcrypt#25]
Oh, hi there. 

Is there any way to use multiple transcrypt keys in the same repo? i.e. encrypt some files with key A and some with key B. 

I can try to write some code if you point me in the right direction. Let me know! Thanks.

**Comment by elasticdog** [comment]
Hey Charlie!

So, it would take quite a bit of tweaking. Basically you'd need a new dedicated section in the config file where it would store the credentials and filter definitions, and then also separate clean/smudge filter scripts that pull in those credentials. Then you'd select which crypt filter to apply to a particular pattern of files in the *.gitattributes* file. That said, the UI would also need updating to manage multiple keys and also pass the safety checks accordingly, so overall it would be a complicated undertaking.

**Comment by elasticdog** [comment]
@charliewolf! Did you end up implementing something for this, or work around it another way? Honestly, I have been neglecting transcrypt as I haven't been using it (personally or professionally) for long time.

**Comment by charliewolf** [comment]
@elasticdog I haven't been using `transcrypt` either. Mainly have used `git-crypt` when I've needed to encrypt things in a repo

**Comment by cdimitroulas** [comment]
@elasticdog what are you using instead of `transcrypt`? I was about to use this library for encrypting some variables in a repo for out team but noticed your comment saying you aren't using this personally or professionally which has kind of put me off...

**Comment by elasticdog** [comment]
@cdimitroulas rather than have secrets stored in the repo itself, we've been using [HashiCorp's Vault](https://www.vaultproject.io/) as a dedicated, highly-available secret store and have various tooling/workflows to pull things out as needed. Lots of advantages to using something like Vault, but certainly more work and infrastructure to manage.
