### ISSUE TITLE
Heroku

### ISSUE THREAD

**Issue by perplexes** [elasticdog/transcrypt#26]
I made a buildpack for heroku so it'll decrypt on deploy!

https://github.com/perplexes/heroku-buildpack-transcrypt

**Comment by elasticdog** [comment]
This is awesome! I just pushed a [commit](https://github.com/elasticdog/transcrypt/commit/f24bf3a6054372e61360cd8b572010c5ee177f4d) that documents your buildpack in a new [INSTALL file](https://github.com/elasticdog/transcrypt/blob/master/INSTALL.md#heroku) and mentioned it in the README as well. Thank you for the contribution and for bringing it to my attention!
