### ISSUE TITLE
Spaces in file name causing issue

### ISSUE THREAD

**Issue by dreamwisdom** [elasticdog/transcrypt#32]
Rekey fails when .gitattribute contains two star in path (**) and they are files with spaces in their name.

https://git-scm.com/docs/gitignore
`A trailing "/**" matches everything inside. For example, "abc/**" matches all files inside directory "abc", relative to the location of the .gitignore file, with infinite depth.`

There was also a unicode character in the filename, but I don't think that was the problem. (à)
I'm on windows.

.gitattributes:
`/private/** filter=crypt diff=crypt`

file:
`the file.txt`

Error:
```
	Proceed with rekey? [y/N] y

touch: unknown option -- N
Try 'touch --help' for more information.
error: private/the: does not exist and --remove not passed
fatal: Unable to process path private/the
***  rekeyed files have been staged  ***
*** COMMIT THESE CHANGES RIGHT AWAY! ***
```

**Comment by dreamwisdom** [comment]
Not sure if its fully working now but I changed this to make it work.
I also couldn't decrypt after checkout.


```
		for file in $encrypted_files; do
			rm "$file"
		done
		git checkout --force HEAD -- "$encrypted_files" > /dev/null
```
to
```		
		IFS="
"
		for file in $encrypted_files; do
			rm "$file"
			git checkout --force HEAD -- "$file" > /dev/null
		done
		IFS=" "
```

**Comment by elasticdog** [comment]
Thank you very much for the bug report. I've pushed a fix to master based on setting `IFS=$'\n'` and also made sure that it works when using the `--show-raw` flag (which was also broken). I've tested file names with spaces, as well as the infinite depth file glob pattern `**`, and various combinations of the two.

Give me a bit and I'll cut a release.
