### ISSUE TITLE
[Q] committing gpg keys

### ISSUE THREAD

**Issue by andreineculau** [elasticdog/transcrypt#43]
I love the simplicity of transcrypt, but I cannot wrap my head around the current integration with gpg in #10 .

`transcrypt --export-gpg <recipient>` ends up saving the credentials of this repo encrypted for `recipient` under `.git/crypt/<recipient>.asc`. For reasons unknown to me, `transcrypt --import-gpg <recipient>` will look for `.git/crypt/<recipient>` or `.git/crypt/<recipient>.asc` or for the file `<recipient>` itself.

Before GPG support, it is clear to me that sharing access to encrypted files is done by sharing the cipher and the password (hopefully via safe communication methods).

But after GPG support, it is unclear to me why sharing access is done by sharing (manually that is) an encrypted message, rather than having the message committed into the repo (implicit sharing; the recipient wouldn't need to store the message since it will always be available in the repo).

How do you imagine the use of the GPG support? What happens if everyone flushes their credentials and they didn't keep a copy of the encrypted message? Default once again to the cipher and password stored somewhere, in a safe location?

That's what I can't wrap my head around. As it is now, GPG support is merely a built-in secure transport of the cipher and password, while I see it as an alternative to cipher and password, because anyone with access to the git repo, and access to one of the secret keys that can decrypt a member's encrypted message, gains access to the encrypted files.

The latter increases the attack surface, but it is more convenient. The former, well, it seems at least, add only overhead (considerable one going from share a password to setup gpg&co) with little gain (as long as the cipher and password are transmitted to the right people via safe communication methods).

Thanks in advance for the explanations!

**Comment by elasticdog** [comment]
The GPG support was modeled almost exactly after what `git-crypt` supported at the time, and was meant specifically as a convenience mechanism to securely share the cipher/password without having to come up with your own safe communication methods. If your usage of GPG is widespread enough in whatever ecosystem where you're using transcrypt, then you could certainly copy them from the local `.git/crypt/` directory and check them into the repository, but I didn't feel that should be a hard requirement. It's still fundamentally a single shared password setup that uses `openssl` under the hood.

Functionality to support additional integration for GPG with keys stored in the repo could be added, but would add a fair bit of complexity, would need some path conventions, and it wouldn't change the security level of the secrets that are encrypted by transcrypt. The same could be said for better integration with tooling provided by https://keybase.io/ or encrypted pastebins, etc. While I'd gladly review PRs if people are interested in developing that functionality, it's not really transcrypt's primary purpose. If support were added for multiple keys and intersections of keys and users, it might make more sense to integrate more deeply.

Hopefully that explanation makes sense?

**Comment by andreineculau** [comment]
Makes lots of sense! Thank you!
So if i hear you correctly you would like to stick to"one thing well" and let the distribution of the keys to be handle by another tool e.g. transcrypt-in-git, transcrypt-in-keybase, transcrypt-in-1password etc

Once again makes lots of sense!

--
http://andreineculau.com
