### ISSUE TITLE
Files not being decrypted

### ISSUE THREAD

**Issue by cdimitroulas** [elasticdog/transcrypt#44]
Hi there,

I set up transcrypt on a repository (let's call it repo `A`) the other day and everything was working fine. I set up transcrypt on a new repository (repo `B`) yesterday and that seems to be working fine as well but now when I started working on the repo `A` again I noticed that my files are not being decrypted locally.
Things are still working fine on repo `B`.

I am not sure why this is happening but I am happy to give you more information if you guide me on where to look!

Edit: Is it possible that a `rebase` could cause this issue?

**Comment by cdimitroulas** [comment]
OK so I solved this by following the first answer here https://stackoverflow.com/questions/21652242/git-re-checkout-files-after-creating-smudge-filter

Feel free to close this issue as I believe it was caused by a `rebase`

**Comment by elasticdog** [comment]
Ahh, glad you found a solution. Rebases can definitely be tricky to handle for filters. I appreciate you updating the issue with your solution.
