### ISSUE TITLE
Missing requirements

### ISSUE THREAD

**Issue by andrew8er** [elasticdog/transcrypt#54]
The transcrypt script needs the `column` command to run. On newer Ubuntu systems, this is provided by the `bsdmainutils` package. It should be added to the requirements list.

**Comment by jeffery** [comment]
I needed this in Ubuntu 18.04

**Comment by jmurty** [comment]
Thanks for the feedback, we will mention the `column` command and the need to install `bsdmainutils` on Ubuntu/Debian in the [next release](https://github.com/elasticdog/transcrypt/pull/84)
