### ISSUE TITLE
WSL not work

### ISSUE THREAD

**Issue by ricardo0624** [elasticdog/transcrypt#61]
in wsl , windows subsystem linux,it now work

**Comment by jmurty** [comment]
Hi @ricardo0624 can you try [this suggested fix for Windows 10](https://github.com/elasticdog/transcrypt/issues/78#issue-606977699) that uses Git's included bash interpreter?

> [T]o install transcrypt on Windows without bash, I simply added it as a git alias and use the built-in bash interpretator in git.
> This is done with `git config --add alias.transcrypt = !~/path/to/transcrypt/transcrypt`
> After this, I can install it with `git transcrypt`.

**Comment by ricardo0624** [comment]
@jmurty thanks a lot,but now I have work in manjaro linux and no longer to need it.
