### ISSUE TITLE
after clone on other server and initialize the transcript, all encrypted files are dirty

### ISSUE THREAD

**Issue by huuub** [elasticdog/transcrypt#66]
I clone my repo, and after running : 
transcrypt -c aes-256-cbc -p 'thinkagain'
My encrypted files become modified. 
So it seems : "Once transcrypt has stored the matching credentials, it will force a checkout of any exising encrypted files in order to decrypt them." -> that step is not happening.

**Comment by elasticdog** [comment]
Hey @huuub, I believe what you're seeing is an expected side effect of the 2.0.0 release, and you can read more about how to fix it in the [release notes](https://github.com/elasticdog/transcrypt/releases/tag/v2.0.0). Feel free to re-open this issue if that doesn't answer your question. Cheers.

**Comment by huuub** [comment]
I don't think so, because I was not using it before version 2.0. 
If I make another commit where it was working and pull again on the faulty one, it is working again. 
Seems that the decrypt by the initialisation marks them all as modified.

**Comment by huuub** [comment]
However I tried this. 
Then on another server cloned it. 
I initialised with the transcrypt -c aes-256-cbc -p '.....'
Again all encrypted files become modified. 
Can't even repeat the proces there because :
transcrypt: the repo is dirty; commit or stash your changes before running transcrypt
