### ISSUE TITLE
List issues with rebasing in README Caveats / Limitations 

### ISSUE THREAD

**Issue by Erotemic** [elasticdog/transcrypt#67]
I think it important to be more upfront about issues with rebasing like those brought up in #8. These limitations should be clearly stated in the README, so fools like myself don't almost push all their secrets in plaintext.

**Comment by jmurty** [comment]
I'm pretty confident that the underlying merge issue is fixed in the pending PR #76 that adds a merge driver to better handle conflicts that occur during rebasing, or merging in general.

**Comment by jmurty** [comment]
The merge and rebase problems should be solved by PR #76 which is now merged to the *master* branch and will be included in the next release.
